function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 0; // obj_disari_gizli_save_b1
	global.__objectDepths[1] = 0; // obj_disari_gizli_save_b2
	global.__objectDepths[2] = 0; // obj_yon
	global.__objectDepths[3] = 1; // obj_karakter
	global.__objectDepths[4] = 1; // obj_karakter_bolum_1_cutscene
	global.__objectDepths[5] = 1; // obj_karakter_bolum_2_cutscene
	global.__objectDepths[6] = 1; // obj_karakter_bolum_2_cutscene_2
	global.__objectDepths[7] = 0; // obj_pistol
	global.__objectDepths[8] = 0; // obj_kursun_pistol
	global.__objectDepths[9] = 1; // obj_agac
	global.__objectDepths[10] = 3; // obj_deniz
	global.__objectDepths[11] = 2; // obj_kaldirim
	global.__objectDepths[12] = 1; // obj_kopru_demir
	global.__objectDepths[13] = 3; // obj_kum
	global.__objectDepths[14] = 2; // obj_yol
	global.__objectDepths[15] = 1; // obj_yol_serit
	global.__objectDepths[16] = 1; // obj_agac_fade
	global.__objectDepths[17] = 0; // obj_baslik
	global.__objectDepths[18] = 0; // obj_oyna
	global.__objectDepths[19] = 0; // obj_ayarlar
	global.__objectDepths[20] = 0; // obj_credits_git
	global.__objectDepths[21] = 0; // obj_cik
	global.__objectDepths[22] = 0; // obj_arkaplan_ses
	global.__objectDepths[23] = 0; // obj_trmenu
	global.__objectDepths[24] = 0; // obj_enmenu
	global.__objectDepths[25] = 0; // obj_durdurma
	global.__objectDepths[26] = 0; // obj_anamenu_durdurma
	global.__objectDepths[27] = 0; // obj_oyun_devam
	global.__objectDepths[28] = 0; // obj_durdurma_kaydetme
	global.__objectDepths[29] = 0; // obj_devam_yukleniyor
	global.__objectDepths[30] = 0; // obj_render_kapasite
	global.__objectDepths[31] = 0; // obj_render_olcek
	global.__objectDepths[32] = 0; // obj_grafik_kapasite
	global.__objectDepths[33] = 0; // obj_grafik_olcek
	global.__objectDepths[34] = 0; // obj_geri
	global.__objectDepths[35] = 0; // obj_yeni_oyun
	global.__objectDepths[36] = 0; // obj_kayitli_oyun
	global.__objectDepths[37] = 0; // obj_yeni_oyun_yukleniyor
	global.__objectDepths[38] = 1; // obj_bina_1
	global.__objectDepths[39] = 1; // obj_bina_2
	global.__objectDepths[40] = 2; // obj_sidewalk_h
	global.__objectDepths[41] = 2; // obj_sidewalk_v
	global.__objectDepths[42] = 1; // obj_ev
	global.__objectDepths[43] = 0; // obj_Deactivate_Parent
	global.__objectDepths[44] = 1; // obj_yaya
	global.__objectDepths[45] = 1; // obj_yaya_2
	global.__objectDepths[46] = 0; // obj_kaydetme_1
	global.__objectDepths[47] = 0; // obj_kaydetme_2
	global.__objectDepths[48] = 0; // obj_facebook
	global.__objectDepths[49] = 3; // obj_bolum_zemin
	global.__objectDepths[50] = 3; // obj_bolum_duvar
	global.__objectDepths[51] = 1; // obj_cutscene_duvar
	global.__objectDepths[52] = 1; // obj_bildirim_alani_part_1
	global.__objectDepths[53] = 1; // obj_bildirimi_alani_part_2
	global.__objectDepths[54] = 0; // obj_bildirimi_alani_part_3
	global.__objectDepths[55] = 1; // obj_final
	global.__objectDepths[56] = 2; // obj_bolum_1_part_2_kapi
	global.__objectDepths[57] = 2; // obj_bolum_1_part_2_part_3
	global.__objectDepths[58] = 2; // obj_bolum_1_part_3_final
	global.__objectDepths[59] = 1; // parent_kati
	global.__objectDepths[60] = 0; // parent_guvenlik
	global.__objectDepths[61] = 2; // obj_kan
	global.__objectDepths[62] = 1; // obj_asagi
	global.__objectDepths[63] = 1; // obj_bolum_1_guvenlik
	global.__objectDepths[64] = 1; // obj_kapi_1
	global.__objectDepths[65] = 1; // obj_kapi_acilma
	global.__objectDepths[66] = 0; // obj_bolum_1_splash
	global.__objectDepths[67] = 0; // obj_bolum_1_splash_2
	global.__objectDepths[68] = 0; // obj_konusma_1_devam_block
	global.__objectDepths[69] = 0; // obj_konusma_2_devam_block
	global.__objectDepths[70] = 0; // obj_bolum_1_kapi_kontrol_1
	global.__objectDepths[71] = 0; // obj_bolum_1_kapi_engeli_part_1
	global.__objectDepths[72] = 0; // obj_bolum_1_8_saat_sonra_kontrol
	global.__objectDepths[73] = 0; // obj_bolum_1_kapi_kontrol_2
	global.__objectDepths[74] = 0; // obj_bolum_1_kapi_engeli_part_2
	global.__objectDepths[75] = 1; // obj_cutscene_koltuk
	global.__objectDepths[76] = 0; // obj_yeni_bolum
	global.__objectDepths[77] = 1; // obj_banka_kasa_kapali
	global.__objectDepths[78] = 0; // obj_karanlik
	global.__objectDepths[79] = 1; // obj_banka_para
	global.__objectDepths[80] = 0; // obj_cutscene_gec
	global.__objectDepths[81] = 0; // obj_guvenlik_mermi
	global.__objectDepths[82] = 1; // obj_bolum_1_baslangic
	global.__objectDepths[83] = 1; // obj_bolum_1_baslangic2
	global.__objectDepths[84] = 1; // obj_bolum_1_8saatsonra
	global.__objectDepths[85] = 1; // obj_bolum_1_konusma1
	global.__objectDepths[86] = 1; // obj_bolum_1_konusma2
	global.__objectDepths[87] = 2; // obj_checkpoint_gorev_2
	global.__objectDepths[88] = 1; // obj_checkpoint_gorev_2_bildirim
	global.__objectDepths[89] = 0; // obj_cutscene_gec_b_2
	global.__objectDepths[90] = 0; // obj_cutscene_gec_b_2_2
	global.__objectDepths[91] = 1; // obj_kukla_talim
	global.__objectDepths[92] = 1; // obj_kukla_olu
	global.__objectDepths[93] = 1; // obj_atis_engel_duvar_b_2
	global.__objectDepths[94] = 0; // obj_talim_vurma_check_1_bildirim
	global.__objectDepths[95] = 0; // obj_talim_vurma_check_2_bildirim
	global.__objectDepths[96] = 0; // obj_talim_vurma_check_3_bildirim
	global.__objectDepths[97] = 0; // obj_ozan_b_2
	global.__objectDepths[98] = 0; // obj_burak_b_2
	global.__objectDepths[99] = 0; // obj_ozan_b_2_2
	global.__objectDepths[100] = 0; // obj_burak_b_2_2
	global.__objectDepths[101] = 2; // obj_bolum_2_konusmaya_gecis_engel_1
	global.__objectDepths[102] = 4; // obj_bolum_2_konusmaya_gecis_engel_2
	global.__objectDepths[103] = 0; // obj_konusma_devam_block_1
	global.__objectDepths[104] = 0; // obj_konusma_devam_block_2
	global.__objectDepths[105] = 0; // obj_konusma_devam_block_3
	global.__objectDepths[106] = 0; // obj_konusma_devam_block_4
	global.__objectDepths[107] = 0; // obj_konusma_devam_block_5
	global.__objectDepths[108] = 1; // obj_bolum_2_konusma1
	global.__objectDepths[109] = 1; // obj_bolum_2_konusma2
	global.__objectDepths[110] = 1; // obj_bolum_2_konusma3
	global.__objectDepths[111] = 1; // obj_bolum_2_konusma4
	global.__objectDepths[112] = 1; // obj_bolum_2_final
	global.__objectDepths[113] = 2; // obj_checkpoint_gorev_3
	global.__objectDepths[114] = 1; // obj_checkpoint_gorev_3_bildirim
	global.__objectDepths[115] = 0; // obj_titanoga_baslangic
	global.__objectDepths[116] = 0; // obj_titanoga_baslangic_collision
	global.__objectDepths[117] = 0; // obj_splash
	global.__objectDepths[118] = 0; // obj_fade
	global.__objectDepths[119] = 0; // obj_yukleniyor
	global.__objectDepths[120] = 0; // obj_oyun_yukleniyor_sarki
	global.__objectDepths[121] = 1; // obj_kayit_1
	global.__objectDepths[122] = 0; // obj_kayit_1_yukleniyor
	global.__objectDepths[123] = 1; // obj_kayit_2
	global.__objectDepths[124] = 0; // obj_kayit_2_yukleniyor
	global.__objectDepths[125] = 0; // obj_kayit_hata
	global.__objectDepths[126] = 0; // obj_kayit_1_sil
	global.__objectDepths[127] = 0; // obj_kayit_2_sil
	global.__objectDepths[128] = 0; // obj_geri_kayitli_oyunlar
	global.__objectDepths[129] = -1000; // obj_credits
	global.__objectDepths[130] = 0; // obj_credits_geri
	global.__objectDepths[131] = 1; // obj_ev_check_giris_bildirim_b_1
	global.__objectDepths[132] = 1; // obj_ev_check_giris_b_1
	global.__objectDepths[133] = 2; // obj_ev_duvar_b_1
	global.__objectDepths[134] = 1; // obj_ev_check_cikis_b_1
	global.__objectDepths[135] = 1; // obj_ev_check_cikis_bildirim_b_1
	global.__objectDepths[136] = 2; // obj_ev_cikis_b_1_solid
	global.__objectDepths[137] = 2; // obj_kayit_1_collision_b_1
	global.__objectDepths[138] = 0; // obj_kayit_1_collision_bildirim_b_1
	global.__objectDepths[139] = 2; // obj_kayit_2_collision_b_1
	global.__objectDepths[140] = 0; // obj_kayit_2_collision_bildirim_b_1
	global.__objectDepths[141] = 1; // obj_ev_check_cikis_bildirim_b_2
	global.__objectDepths[142] = 1; // obj_ev_check_cikis_b_2
	global.__objectDepths[143] = 2; // obj_ev_check_giris_b_2
	global.__objectDepths[144] = 1; // obj_ev_check_giris_bildirim_b_2
	global.__objectDepths[145] = 0; // obj_gameload
	global.__objectDepths[146] = 0; // obj_ev_ok_b1
	global.__objectDepths[147] = 0; // obj_ev_ok_b2
	global.__objectDepths[148] = 0; // obj_ev_yon
	global.__objectDepths[149] = 0; // obj_hud_main
	global.__objectDepths[150] = 2; // arkaplanx
	global.__objectDepths[151] = 0; // obj_hata
	global.__objectDepths[152] = 0; // obj_geri_menu
	global.__objectDepths[153] = 0; // obj_geri_oynama


	global.__objectNames[0] = "obj_disari_gizli_save_b1";
	global.__objectNames[1] = "obj_disari_gizli_save_b2";
	global.__objectNames[2] = "obj_yon";
	global.__objectNames[3] = "obj_karakter";
	global.__objectNames[4] = "obj_karakter_bolum_1_cutscene";
	global.__objectNames[5] = "obj_karakter_bolum_2_cutscene";
	global.__objectNames[6] = "obj_karakter_bolum_2_cutscene_2";
	global.__objectNames[7] = "obj_pistol";
	global.__objectNames[8] = "obj_kursun_pistol";
	global.__objectNames[9] = "obj_agac";
	global.__objectNames[10] = "obj_deniz";
	global.__objectNames[11] = "obj_kaldirim";
	global.__objectNames[12] = "obj_kopru_demir";
	global.__objectNames[13] = "obj_kum";
	global.__objectNames[14] = "obj_yol";
	global.__objectNames[15] = "obj_yol_serit";
	global.__objectNames[16] = "obj_agac_fade";
	global.__objectNames[17] = "obj_baslik";
	global.__objectNames[18] = "obj_oyna";
	global.__objectNames[19] = "obj_ayarlar";
	global.__objectNames[20] = "obj_credits_git";
	global.__objectNames[21] = "obj_cik";
	global.__objectNames[22] = "obj_arkaplan_ses";
	global.__objectNames[23] = "obj_trmenu";
	global.__objectNames[24] = "obj_enmenu";
	global.__objectNames[25] = "obj_durdurma";
	global.__objectNames[26] = "obj_anamenu_durdurma";
	global.__objectNames[27] = "obj_oyun_devam";
	global.__objectNames[28] = "obj_durdurma_kaydetme";
	global.__objectNames[29] = "obj_devam_yukleniyor";
	global.__objectNames[30] = "obj_render_kapasite";
	global.__objectNames[31] = "obj_render_olcek";
	global.__objectNames[32] = "obj_grafik_kapasite";
	global.__objectNames[33] = "obj_grafik_olcek";
	global.__objectNames[34] = "obj_geri";
	global.__objectNames[35] = "obj_yeni_oyun";
	global.__objectNames[36] = "obj_kayitli_oyun";
	global.__objectNames[37] = "obj_yeni_oyun_yukleniyor";
	global.__objectNames[38] = "obj_bina_1";
	global.__objectNames[39] = "obj_bina_2";
	global.__objectNames[40] = "obj_sidewalk_h";
	global.__objectNames[41] = "obj_sidewalk_v";
	global.__objectNames[42] = "obj_ev";
	global.__objectNames[43] = "obj_Deactivate_Parent";
	global.__objectNames[44] = "obj_yaya";
	global.__objectNames[45] = "obj_yaya_2";
	global.__objectNames[46] = "obj_kaydetme_1";
	global.__objectNames[47] = "obj_kaydetme_2";
	global.__objectNames[48] = "obj_facebook";
	global.__objectNames[49] = "obj_bolum_zemin";
	global.__objectNames[50] = "obj_bolum_duvar";
	global.__objectNames[51] = "obj_cutscene_duvar";
	global.__objectNames[52] = "obj_bildirim_alani_part_1";
	global.__objectNames[53] = "obj_bildirimi_alani_part_2";
	global.__objectNames[54] = "obj_bildirimi_alani_part_3";
	global.__objectNames[55] = "obj_final";
	global.__objectNames[56] = "obj_bolum_1_part_2_kapi";
	global.__objectNames[57] = "obj_bolum_1_part_2_part_3";
	global.__objectNames[58] = "obj_bolum_1_part_3_final";
	global.__objectNames[59] = "parent_kati";
	global.__objectNames[60] = "parent_guvenlik";
	global.__objectNames[61] = "obj_kan";
	global.__objectNames[62] = "obj_asagi";
	global.__objectNames[63] = "obj_bolum_1_guvenlik";
	global.__objectNames[64] = "obj_kapi_1";
	global.__objectNames[65] = "obj_kapi_acilma";
	global.__objectNames[66] = "obj_bolum_1_splash";
	global.__objectNames[67] = "obj_bolum_1_splash_2";
	global.__objectNames[68] = "obj_konusma_1_devam_block";
	global.__objectNames[69] = "obj_konusma_2_devam_block";
	global.__objectNames[70] = "obj_bolum_1_kapi_kontrol_1";
	global.__objectNames[71] = "obj_bolum_1_kapi_engeli_part_1";
	global.__objectNames[72] = "obj_bolum_1_8_saat_sonra_kontrol";
	global.__objectNames[73] = "obj_bolum_1_kapi_kontrol_2";
	global.__objectNames[74] = "obj_bolum_1_kapi_engeli_part_2";
	global.__objectNames[75] = "obj_cutscene_koltuk";
	global.__objectNames[76] = "obj_yeni_bolum";
	global.__objectNames[77] = "obj_banka_kasa_kapali";
	global.__objectNames[78] = "obj_karanlik";
	global.__objectNames[79] = "obj_banka_para";
	global.__objectNames[80] = "obj_cutscene_gec";
	global.__objectNames[81] = "obj_guvenlik_mermi";
	global.__objectNames[82] = "obj_bolum_1_baslangic";
	global.__objectNames[83] = "obj_bolum_1_baslangic2";
	global.__objectNames[84] = "obj_bolum_1_8saatsonra";
	global.__objectNames[85] = "obj_bolum_1_konusma1";
	global.__objectNames[86] = "obj_bolum_1_konusma2";
	global.__objectNames[87] = "obj_checkpoint_gorev_2";
	global.__objectNames[88] = "obj_checkpoint_gorev_2_bildirim";
	global.__objectNames[89] = "obj_cutscene_gec_b_2";
	global.__objectNames[90] = "obj_cutscene_gec_b_2_2";
	global.__objectNames[91] = "obj_kukla_talim";
	global.__objectNames[92] = "obj_kukla_olu";
	global.__objectNames[93] = "obj_atis_engel_duvar_b_2";
	global.__objectNames[94] = "obj_talim_vurma_check_1_bildirim";
	global.__objectNames[95] = "obj_talim_vurma_check_2_bildirim";
	global.__objectNames[96] = "obj_talim_vurma_check_3_bildirim";
	global.__objectNames[97] = "obj_ozan_b_2";
	global.__objectNames[98] = "obj_burak_b_2";
	global.__objectNames[99] = "obj_ozan_b_2_2";
	global.__objectNames[100] = "obj_burak_b_2_2";
	global.__objectNames[101] = "obj_bolum_2_konusmaya_gecis_engel_1";
	global.__objectNames[102] = "obj_bolum_2_konusmaya_gecis_engel_2";
	global.__objectNames[103] = "obj_konusma_devam_block_1";
	global.__objectNames[104] = "obj_konusma_devam_block_2";
	global.__objectNames[105] = "obj_konusma_devam_block_3";
	global.__objectNames[106] = "obj_konusma_devam_block_4";
	global.__objectNames[107] = "obj_konusma_devam_block_5";
	global.__objectNames[108] = "obj_bolum_2_konusma1";
	global.__objectNames[109] = "obj_bolum_2_konusma2";
	global.__objectNames[110] = "obj_bolum_2_konusma3";
	global.__objectNames[111] = "obj_bolum_2_konusma4";
	global.__objectNames[112] = "obj_bolum_2_final";
	global.__objectNames[113] = "obj_checkpoint_gorev_3";
	global.__objectNames[114] = "obj_checkpoint_gorev_3_bildirim";
	global.__objectNames[115] = "obj_titanoga_baslangic";
	global.__objectNames[116] = "obj_titanoga_baslangic_collision";
	global.__objectNames[117] = "obj_splash";
	global.__objectNames[118] = "obj_fade";
	global.__objectNames[119] = "obj_yukleniyor";
	global.__objectNames[120] = "obj_oyun_yukleniyor_sarki";
	global.__objectNames[121] = "obj_kayit_1";
	global.__objectNames[122] = "obj_kayit_1_yukleniyor";
	global.__objectNames[123] = "obj_kayit_2";
	global.__objectNames[124] = "obj_kayit_2_yukleniyor";
	global.__objectNames[125] = "obj_kayit_hata";
	global.__objectNames[126] = "obj_kayit_1_sil";
	global.__objectNames[127] = "obj_kayit_2_sil";
	global.__objectNames[128] = "obj_geri_kayitli_oyunlar";
	global.__objectNames[129] = "obj_credits";
	global.__objectNames[130] = "obj_credits_geri";
	global.__objectNames[131] = "obj_ev_check_giris_bildirim_b_1";
	global.__objectNames[132] = "obj_ev_check_giris_b_1";
	global.__objectNames[133] = "obj_ev_duvar_b_1";
	global.__objectNames[134] = "obj_ev_check_cikis_b_1";
	global.__objectNames[135] = "obj_ev_check_cikis_bildirim_b_1";
	global.__objectNames[136] = "obj_ev_cikis_b_1_solid";
	global.__objectNames[137] = "obj_kayit_1_collision_b_1";
	global.__objectNames[138] = "obj_kayit_1_collision_bildirim_b_1";
	global.__objectNames[139] = "obj_kayit_2_collision_b_1";
	global.__objectNames[140] = "obj_kayit_2_collision_bildirim_b_1";
	global.__objectNames[141] = "obj_ev_check_cikis_bildirim_b_2";
	global.__objectNames[142] = "obj_ev_check_cikis_b_2";
	global.__objectNames[143] = "obj_ev_check_giris_b_2";
	global.__objectNames[144] = "obj_ev_check_giris_bildirim_b_2";
	global.__objectNames[145] = "obj_gameload";
	global.__objectNames[146] = "obj_ev_ok_b1";
	global.__objectNames[147] = "obj_ev_ok_b2";
	global.__objectNames[148] = "obj_ev_yon";
	global.__objectNames[149] = "obj_hud_main";
	global.__objectNames[150] = "arkaplanx";
	global.__objectNames[151] = "obj_hata";
	global.__objectNames[152] = "obj_geri_menu";
	global.__objectNames[153] = "obj_geri_oynama";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
